Fixes to make sure that mercury-install does not attempt to install packages that are already installed

diff --git a/mercury/mercury-install b/mercury/mercury-install
--- a/mercury/mercury-install
+++ b/mercury/mercury-install
@@ -11,6 +11,7 @@ fi
 
 install_package() {
     local PACKAGE=$1
+    # This check is mostly redundant since the offical release of version 1.0, but just incase there is a special case that the remove already installed packages loop doesn't get, I am leaving this in. This can be removed to reduce line count
     if cat $INSTALL_PATH/etc/installed_package | grep -x $PACKAGE; then
         echo "$PACKAGE is already installed, skipping"
         return 1
@@ -41,6 +42,17 @@ install_package() {
 
 get_depends() {
 
+
+# If there is only 1 package in the queue, check to see if that package is installed.  This is just for looks, all it does is make sure that getting dependencies does not pop up when there is only 1 package, this can be removed if line count is prefered over looks.
+local numpkg=$(echo $packages | wc -w)
+if [[ $numpkg == 1 ]]; then
+  if cat $INSTALL_PATH/etc/installed_package | grep -x $package >/dev/null; then
+	  packages=""
+	  return 0
+  fi
+fi
+
+
 echo "Getting Dependencies"
 until [ "$packages" == "$packageold" ] 
 do
@@ -61,26 +73,39 @@ packages=$( awk 'BEGIN{RS=ORS=" "}!a[$0]++' <<<$packages );
 # Take the mutliline packages variable and convert it to a single line
 packages=$(echo "$packages" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-) 
 
-# Remove any already installed packages
+
+# Remove any already installed packages. This works by only adding packages to a new variable if they are NOT installed, at the end the new variable is set to the packages variable
 for package in ${packages[@]}
 do
-   if cat $INSTALL_PATH/etc/installed_package | grep -x $package >/dev/null; then
-     packages=$(echo $packages | sed "s/\ $package\ /\ /")
-   fi
+  if cat $INSTALL_PATH/etc/installed_package | grep -x $package >/dev/null; then
+     :
+  else
+     packages_new=$(echo "$packages_new $package")	  
+  fi
+done
+
+packages=$packages_new
+
+
+}
+
+check_if_packages_exist() {
+
+# Make sure the root (actually inputed) packages exist, this check is repeated for the depends (I mess up some times with the depend files) 
+for package in ${packages[@]}
+do
+   if [[ $(cat $INSTALL_PATH/var/cache/mercury/available-packages | grep -x $package | wc -c) == 0 ]]
+   then
+           echo "$package was not found, exiting"
+           exit 1
+   fi  
 done
 
 }
 
 
-# Make sure the root (actually inputed packages) exist, this check is repeated for the depends (I mess up some times)
-for package in ${packages[@]}
-do
-   if [[ $(cat $INSTALL_PATH/var/cache/mercury/available-packages | grep -x $package | wc -c) == 0 ]]
-   then
-	   echo "$package was not found, exiting"
-	   exit 1
-   fi
-done
+# Run the check function
+check_if_packages_exist
 
 # Run the depends function
 get_depends
@@ -88,18 +113,11 @@ get_depends
 
 
 numpackage=$(wc -w <<< $packages)
-#Basically the same thing but just for safety lol
+# Basically the same thing but just for safety lol
 pkgnoline=$(tr "\n" " " <<< $packages)
 
-#Sanity check to make sure that all packages exist (Same as above)
-for package in ${packages[@]}
-do
-   if [[ $(cat $INSTALL_PATH/var/cache/mercury/available-packages | grep -x $package | wc -c) == 0 ]]
-   then
-	   echo "$package was not found, exiting"
-	   exit 1
-   fi
-done
+# Sanity check to make sure that all packages exist (See function for details)
+check_if_packages_exist
 
 
 if test $numpackage -ne 0; then
@@ -120,7 +138,5 @@ if test $numpackage -ne 0; then
   ;;
  esac
  else 
-  printf "\n\nNothing to do all packages are installed\n"
+  printf "Nothing to do all packages are installed\n"
 fi
-
-
