Mercury updates

diff --git a/mercury/mercury-install b/mercury/mercury-install
--- a/mercury/mercury-install
+++ b/mercury/mercury-install
@@ -10,6 +10,27 @@ if [[ $EUID -ne 0 ]]; then
    exit 1
 fi
 
+check_online() {
+
+   cd /tmp
+   wget $REPO/available-packages/sha256 &> /dev/null
+   if [[ $? != 0 ]]; then
+     echo "ERROR: Server not reachable or doesn't contain repo files"
+     exit 1
+   fi
+
+
+}
+
+
+generate_file_list() {
+  local PACKAGE=$1
+  cd $INSTALL_PATH/var/cache/mercury/$PACKAGE
+  touch /var/cache/mercury/file-lists/$PACKAGE.list
+  # File lists are always generated for the root directory
+  echo "/$(find * -type f)" > /var/cache/mercury/file-lists/$PACKAGE.list
+
+}
 
 install_package() {
     local PACKAGE=$1
@@ -28,6 +49,9 @@ install_package() {
         echo "Installing $PACKAGE..."
         echo "Extracting $PACKAGE..."
         tar -xpf $PACKAGE.tar.xz
+
+        echo "Generating File list"
+        generate_file_list "$PACKAGE"
 
         echo "Copying contents..."
 	cp -rp $PACKAGE/* $INSTALL_PATH
@@ -104,6 +128,9 @@ do
 done
 
 }
+
+# Check if the server is online
+check_online
 
 
 # Run the check function
diff --git a/mercury/mercury-reinstall b/mercury/mercury-reinstall
--- a/mercury/mercury-reinstall
+++ b/mercury/mercury-reinstall
@@ -2,13 +2,24 @@
 REPO="http://192.168.1.143:88"
 INSTALL_PATH=/mnt
 packages=$@
-# Built For Tucana Version 2.0
+# Built For Tucana Version 3.0
 # DO NOT Use this version (git) on an actual tucana system without changing the INSTALL_PATH   to /  and the REPO_PATH  and uncommeting the bash postinst line
 
 if [[ $EUID -ne 0 ]]; then
    echo "This package manager must be run as root" 
    exit 1
 fi
+
+check_online() {
+
+   cd /tmp
+   wget $REPO/available-packages/sha256 &> /dev/null
+   if [[ $? != 0 ]]; then
+     echo "ERROR: Server not reachable or doesn't contain repo files"
+     exit 1
+   fi
+}
+
 
 move() {
    # This function is so that if packages or files have to be overwriten, the system does not crash while doing it, mostly for updating and reinstalling
@@ -73,7 +84,8 @@ done
 
 }
 
-
+# Check online
+check_online
 # Run the check function
 check_if_packages_exist
 
diff --git a/mercury/mercury-sync b/mercury/mercury-sync
--- a/mercury/mercury-sync
+++ b/mercury/mercury-sync
@@ -1,8 +1,25 @@
 #!/bin/bash
 REPO=http://192.168.1.143:88
 INSTALL_PATH=/mnt
-# Build For Tucana Version 1.0
+# Build For Tucana Version 3.0
+
+check_online() {
+
+   cd /tmp
+   wget $REPO/available-packages/sha256 &> /dev/null
+   if [[ $? != 0 ]]; then
+     echo "ERROR: Server not reachable or doesn't contain repo files"
+     exit 1
+   fi
+
+
+}
+
+check_online
+
+
 mkdir -p $INSTALL_PATH/var/cache/mercury/depend $INSTALL_PATH/etc
+mkdir -p $INSTALL_PATH/var/cache/mercury/file-list/
 touch $INSTALL_PATH/etc/installed_package
 cd $INSTALL_PATH/var/cache/mercury/depend
 echo "Getting Available Packages"
diff --git a/mercury/mercury-update b/mercury/mercury-update
--- a/mercury/mercury-update
+++ b/mercury/mercury-update
@@ -8,6 +8,19 @@ if [[ $EUID -ne 0 ]]; then
    exit 1
 fi
 
+
+check_online() {
+
+   cd /tmp
+   wget $REPO/available-packages/sha256 &> /dev/null
+   if [[ $? != 0 ]]; then
+     echo "ERROR: Server not reachable or doesn't contain repo files"
+     exit 1
+   fi
+
+
+}
+
 move() {
    # This function is so that if packages or files have to be overwriten, the system does not crash while doing it, mostly for updating 
    local folpath=$1
@@ -54,6 +67,10 @@ update_package() {
         echo  "Removing Cache"
         rm -rf $INSTALL_PATH/var/cache/mercury/$PACKAGE*
 }
+
+# Check Online
+check_online
+
 # Get all the available updates
 updates=$(diff $INSTALL_PATH/var/cache/mercury/current $INSTALL_PATH/var/cache/mercury/sha256|grep ">"|cut -c 3- | cut -c67- | sed 's|.tar.xz||g')
 
